# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  groups:
    all-go-mod-patch-and-minor:
      patterns: ["*"]
      update-types: ["patch", "minor"]
  allow:
  # Allow updates for indirect dependencies
  - dependency-type: "all"
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: monthly
    time: "07:00"
  open-pull-requests-limit: 10
