# Build Archlinux packages with drone
#
#     docker build --rm=true -t mikkeloscar/drone-pkgbuild-test \
#       -f Dockerfile.test .

FROM mikkeloscar/drone-pkgbuild:latest
MAINTAINER Mikkel Oscar Lyderik <mikkeloscar@gmail.com>

# parent image switches to build user, switch back to root
USER root

# Install go
RUN pacman -Syu go --noconfirm
# Clean .pacnew files
RUN find / -name "*.pacnew" -exec rename .pacnew '' '{}' \;
# Clean pkg cache
RUN find /var/cache/pacman/pkg -mindepth 1 -delete

# copy local src files to container workspace.
ADD . /go/src/github.com/mikkeloscar/drone-pkgbuild/
RUN chown "$UGNAME:$UGNAME" /go -R

# switch to non-root user
USER $UGNAME

# set $GOPATH
ENV GOPATH /go

# get go deps
RUN go get -t github.com/mikkeloscar/drone-pkgbuild/...

# set workdir
WORKDIR /go/src/github.com/mikkeloscar/drone-pkgbuild

ENTRYPOINT ["go", "test"]
