# Build Archlinux packages with drone
#
#     docker build --rm=true -t mikkeloscar/maze-drone-test \
#       -f Dockerfile.test .

FROM mikkeloscar/maze-drone:latest
MAINTAINER Mikkel Oscar Lyderik <mikkeloscar@gmail.com>

# parent image switches to build user, switch back to root
USER root

# Install go
RUN \
    pacman -Syu go --noconfirm && \
    # Clean .pacnew files
    find / -name "*.pacnew" -exec rename .pacnew '' '{}' \; && \
    # Clean pkg cache
    find /var/cache/pacman/pkg -mindepth 1 -delete

# Add sudoers.test
COPY contrib/etc/sudoers.test /etc/sudoers
RUN chmod 'u=r,g=r,o=' /etc/sudoers

# copy local src files to container workspace.
ADD . /go/src/github.com/mikkeloscar/maze-drone/
RUN chown "$UGNAME:$UGNAME" /go -R

# switch to non-root user
USER $UGNAME

# set $GOPATH
ENV GOPATH /go

# set $DOCKER_TEST for tests run inside docker
ENV DOCKER_TEST 1

# get go deps
RUN go get -t github.com/mikkeloscar/maze-drone/...

# set workdir
WORKDIR /go/src/github.com/mikkeloscar/maze-drone

ENTRYPOINT ["go", "test"]
